development: &default
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= "'#{ENV['DB_PASSWORD']}'" %>
  port: <%= ENV['DB_PORT'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production: &production
  <<: *default
